"""Offline training script for the two ML models this project actually
ships and uses at runtime (see `ml_models.py`):

1. `IsolationForest` -- genuinely unsupervised anomaly detection, trained
   only on *normal* synthetic sequences. At runtime it scores how far a
   fresh reading window sits from the shape of normal operation it learned,
   with no notion of "failure" baked in.
2. `GradientBoostingClassifier` -- genuinely supervised failure-risk
   classification, trained on labeled synthetic sequences (0 = stayed
   healthy, 1 = ended in a failure state), producing a calibrated-ish
   probability plus global feature importances.

Both are trained on synthetic data generated by `telemetry_sim.py`, across
all three asset types at once (see `features.py` for why that generalizes).
This is a demo, not a production fleet -- there is no real historical
telemetry to train on, and the README says so explicitly. Run this script
whenever the simulator's degradation model changes; it overwrites the
`models/*.joblib` artifacts committed to the repo.

Run: python -m backend.train_models
"""
from __future__ import annotations

import json
import logging
from pathlib import Path

import joblib
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier, IsolationForest
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score

from .features import FEATURE_NAMES, extract_features
from .locations import ASSET_TYPES
from .telemetry_sim import generate_training_sequences

logging.basicConfig(level=logging.INFO)
log = logging.getLogger("train_models")

MODELS_DIR = Path(__file__).resolve().parent / "models"
SEQ_LEN = 8


def _build_dataset():
    X, y = [], []
    for asset_type in ASSET_TYPES:
        sequences, labels = generate_training_sequences(
            asset_type, n_normal=500, n_failing=200, seq_len=SEQ_LEN, seed=hash(asset_type) % 1000
        )
        for seq, label in zip(sequences, labels):
            X.append(extract_features(seq, asset_type))
            y.append(label)
    return np.array(X), np.array(y)


def main():
    MODELS_DIR.mkdir(exist_ok=True)
    X, y = _build_dataset()
    log.info("dataset: %d samples, %d features, %d positive (failing)", len(X), X.shape[1], int(y.sum()))

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.25, random_state=42, stratify=y
    )

    # --- Anomaly model: unsupervised, sees ONLY the normal (label=0) training
    # rows. It never sees a labeled failure during training -- it just learns
    # what "normal" looks like across all three asset types and flags
    # anything that doesn't fit that shape.
    X_train_normal = X_train[y_train == 0]
    anomaly_model = IsolationForest(
        n_estimators=200, contamination=0.05, random_state=42
    )
    anomaly_model.fit(X_train_normal)

    # Sanity check: the model should score held-out failing sequences as
    # more anomalous (lower decision_function) than held-out normal ones.
    normal_scores = anomaly_model.decision_function(X_test[y_test == 0])
    failing_scores = anomaly_model.decision_function(X_test[y_test == 1])
    log.info(
        "anomaly model sanity: mean score normal=%.3f  failing=%.3f (failing should be lower)",
        normal_scores.mean(), failing_scores.mean(),
    )
    assert failing_scores.mean() < normal_scores.mean(), (
        "IsolationForest did not learn to separate failing sequences from normal ones -- "
        "check the synthetic data generator before shipping this model"
    )

    # --- Failure-risk model: supervised, sees both classes and their labels.
    failure_model = GradientBoostingClassifier(
        n_estimators=150, max_depth=3, learning_rate=0.1, random_state=42
    )
    failure_model.fit(X_train, y_train)

    proba_test = failure_model.predict_proba(X_test)[:, 1]
    auc = roc_auc_score(y_test, proba_test)
    log.info("failure-risk model held-out ROC-AUC: %.3f", auc)
    assert auc > 0.85, f"failure-risk model AUC too low ({auc:.3f}) to ship -- check training data/features"

    joblib.dump(anomaly_model, MODELS_DIR / "anomaly_model.joblib")
    joblib.dump(failure_model, MODELS_DIR / "failure_model.joblib")

    importances = sorted(
        zip(FEATURE_NAMES, failure_model.feature_importances_.tolist()),
        key=lambda kv: kv[1], reverse=True,
    )
    metadata = {
        "feature_names": FEATURE_NAMES,
        "sequence_length": SEQ_LEN,
        "n_train_samples": int(len(X_train)),
        "n_test_samples": int(len(X_test)),
        "held_out_roc_auc": round(float(auc), 4),
        "feature_importances": [{"feature": f, "importance": round(v, 4)} for f, v in importances],
        "trained_on": "synthetic telemetry only (telemetry_sim.py) -- no real fleet history exists for this demo",
    }
    (MODELS_DIR / "metadata.json").write_text(json.dumps(metadata, indent=2, ensure_ascii=False))

    log.info("saved anomaly_model.joblib, failure_model.joblib, metadata.json to %s", MODELS_DIR)
    log.info("top features by importance: %s", importances[:3])


if __name__ == "__main__":
    main()
